//
// Generated file, do not edit! Created by nedtool 5.0 from src/SDH/SDH_Packet.msg.
//

#ifndef __SDH_PACKET_M_H
#define __SDH_PACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/SDH/SDH_Packet.msg:15</tt> by nedtool.
 * <pre>
 * //
 * // Represents a packet in the network.
 * //
 * packet SDH_Packet
 * {
 *     int inType;
 * }
 * </pre>
 */
class SDH_Packet : public ::omnetpp::cPacket
{
  protected:
    int inType;

  private:
    void copy(const SDH_Packet& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SDH_Packet&);

  public:
    SDH_Packet(const char *name=nullptr, int kind=0);
    SDH_Packet(const SDH_Packet& other);
    virtual ~SDH_Packet();
    SDH_Packet& operator=(const SDH_Packet& other);
    virtual SDH_Packet *dup() const {return new SDH_Packet(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getInType() const;
    virtual void setInType(int inType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SDH_Packet& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SDH_Packet& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SDH_PACKET_M_H

